# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYsLxiQ1m0pEDTFJKAZfyRrz4npBUfPT
"""

import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# =========================
# SETUP MLFLOW
# =========================
mlflow.set_experiment("HR_Attrition_Experiment")

# PENTING: AUTolog AKTIF
mlflow.autolog(log_models=True)

# =========================
# LOAD DATASET
# =========================
df = pd.read_csv("ibm_hr_attrition_preprocessed.csv")

X = df.drop("Attrition", axis=1)
y = df["Attrition"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# =========================
# TRAIN MODEL (TANPA TUNING)
# =========================
model = LogisticRegression(
    max_iter=1000,
    solver="liblinear"
)

with mlflow.start_run():

    model.fit(X_train, y_train)

    # =========================
    # EVALUATION
    # =========================
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)

    # Manual log metric (boleh, tapi autolog tetap jalan)
    mlflow.log_metric("accuracy_manual", acc)
    mlflow.log_metric("f1_score_manual", f1)
    mlflow.log_metric("precision_manual", prec)
    mlflow.log_metric("recall_manual", rec)

print("Training selesai. Artefak MLflow tersimpan.")